add module of vpn_gateway
alibabacloud-automation/terraform-alicloud-vpn-gateway pull request #1
Opened 2019-04-10 13:31 UTC by ali-zhuyu

2019-04-10 13:31 UTC, ali-zhuyu commented
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

alicloud_vpn_gateway.vpngw: Refreshing state... (ID: vpn-2ze2zmfyzsxd7yn2h7w7h)
alicloud_vpn_customer_gateway.vpncgw: Refreshing state... (ID: cgw-2zetmam3uzm9ucmkqnuhy)
alicloud_vpn_connection.connection: Refreshing state... (ID: vco-2ze75q71p8cn9j0y2xbu2)
alicloud_ssl_vpn_server.sslserver: Refreshing state... (ID: vss-2zexy49lyolultz0v6gge)
alicloud_ssl_vpn_client_cert.certs[0]: Refreshing state... (ID: vsc-2zen4d8phijvxt4dbjcbs)
alicloud_ssl_vpn_client_cert.certs[1]: Refreshing state... (ID: vsc-2zeyhqn5n3f29rai5n4mf)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + module.vpn.alicloud_ssl_vpn_client_cert.certs[0]
      id:                            <computed>
      name:                          "vsc-instance-name1"
      ssl_vpn_server_id:             "${alicloud_ssl_vpn_server.sslserver.id}"
      status:                        <computed>

  + module.vpn.alicloud_ssl_vpn_client_cert.certs[1]
      id:                            <computed>
      name:                          "vsc-instance-name2"
      ssl_vpn_server_id:             "${alicloud_ssl_vpn_server.sslserver.id}"
      status:                        <computed>

  + module.vpn.alicloud_ssl_vpn_server.sslserver
      id:                            <computed>
      cipher:                        "AES-128-CBC"
      client_ip_pool:                "192.168.10.0/24"
      compress:                      "false"
      connections:                   <computed>
      internet_ip:                   <computed>
      local_subnet:                  "172.16.1.0/24"
      max_connections:               <computed>
      name:                          "vss-instance-name"
      port:                          "1194"
      protocol:                      "UDP"
      vpn_gateway_id:                "${alicloud_vpn_gateway.vpngw.id}"

  + module.vpn.alicloud_vpn_connection.connection
      id:                            <computed>
      customer_gateway_id:           "${var.cgw_id != \"\" ? var.cgw_id : alicloud_vpn_customer_gateway.vpncgw.id}"
      effect_immediately:            "true"
      ike_config.#:                  "1"
      ike_config.0.ike_auth_alg:     "md5"
      ike_config.0.ike_enc_alg:      "des"
      ike_config.0.ike_lifetime:     "86400"
      ike_config.0.ike_local_id:     "test-local-id"
      ike_config.0.ike_mode:         "main"
      ike_config.0.ike_pfs:          "group1"
      ike_config.0.ike_remote_id:    "test-remote-id"
      ike_config.0.ike_version:      "ikev2"
      ike_config.0.psk:              "tf-testvpn"
      ipsec_config.#:                "1"
      ipsec_config.0.ipsec_auth_alg: "md5"
      ipsec_config.0.ipsec_enc_alg:  "des"
      ipsec_config.0.ipsec_lifetime: "8640"
      ipsec_config.0.ipsec_pfs:      "group5"
      local_subnet.#:                "2"
      local_subnet.2201616582:       "192.168.1.0/24"
      local_subnet.3000113755:       "192.168.2.0/24"
      name:                          "vco-instance-name"
      remote_subnet.#:               "2"
      remote_subnet.1474686024:      "172.16.3.0/24"
      remote_subnet.4052936700:      "172.16.2.0/24"
      status:                        <computed>
      vpn_gateway_id:                "${alicloud_vpn_gateway.vpngw.id}"

  + module.vpn.alicloud_vpn_customer_gateway.vpncgw
      id:                            <computed>
      description:                   "xxxxxx"
      ip_address:                    "21.37.166.152"
      name:                          "cgw-instance-name"

  + module.vpn.alicloud_vpn_gateway.vpngw
      id:                            <computed>
      bandwidth:                     "10"
      business_status:               <computed>
      description:                   "xxxxx"
      enable_ipsec:                  "true"
      enable_ssl:                    "true"
      instance_charge_type:          "PostPaid"
      internet_ip:                   <computed>
      name:                          "vpn-instance-name"
      period:                        "1"
      ssl_connections:               "5"
      status:                        <computed>
      vpc_id:                        "vpc-2ze26284hzdqxew4nll0t"


Plan: 6 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

2019-04-10 13:32 UTC, ali-zhuyu commented
terraform apply
alicloud_vpn_customer_gateway.vpncgw: Refreshing state... (ID: cgw-2zetmam3uzm9ucmkqnuhy)
alicloud_vpn_gateway.vpngw: Refreshing state... (ID: vpn-2ze2zmfyzsxd7yn2h7w7h)
alicloud_ssl_vpn_server.sslserver: Refreshing state... (ID: vss-2zexy49lyolultz0v6gge)
alicloud_vpn_connection.connection: Refreshing state... (ID: vco-2ze75q71p8cn9j0y2xbu2)
alicloud_ssl_vpn_client_cert.certs[1]: Refreshing state... (ID: vsc-2zeyhqn5n3f29rai5n4mf)
alicloud_ssl_vpn_client_cert.certs[0]: Refreshing state... (ID: vsc-2zen4d8phijvxt4dbjcbs)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + module.vpn.alicloud_ssl_vpn_client_cert.certs[0]
      id:                            <computed>
      name:                          "vsc-instance-name1"
      ssl_vpn_server_id:             "${alicloud_ssl_vpn_server.sslserver.id}"
      status:                        <computed>

  + module.vpn.alicloud_ssl_vpn_client_cert.certs[1]
      id:                            <computed>
      name:                          "vsc-instance-name2"
      ssl_vpn_server_id:             "${alicloud_ssl_vpn_server.sslserver.id}"
      status:                        <computed>

  + module.vpn.alicloud_ssl_vpn_server.sslserver
      id:                            <computed>
      cipher:                        "AES-128-CBC"
      client_ip_pool:                "192.168.10.0/24"
      compress:                      "false"
      connections:                   <computed>
      internet_ip:                   <computed>
      local_subnet:                  "172.16.1.0/24"
      max_connections:               <computed>
      name:                          "vss-instance-name"
      port:                          "1194"
      protocol:                      "UDP"
      vpn_gateway_id:                "${alicloud_vpn_gateway.vpngw.id}"

  + module.vpn.alicloud_vpn_connection.connection
      id:                            <computed>
      customer_gateway_id:           "${var.cgw_id != \"\" ? var.cgw_id : alicloud_vpn_customer_gateway.vpncgw.id}"
      effect_immediately:            "true"
      ike_config.#:                  "1"
      ike_config.0.ike_auth_alg:     "md5"
      ike_config.0.ike_enc_alg:      "des"
      ike_config.0.ike_lifetime:     "86400"
      ike_config.0.ike_local_id:     "test-local-id"
      ike_config.0.ike_mode:         "main"
      ike_config.0.ike_pfs:          "group1"
      ike_config.0.ike_remote_id:    "test-remote-id"
      ike_config.0.ike_version:      "ikev2"
      ike_config.0.psk:              "tf-testvpn"
      ipsec_config.#:                "1"
      ipsec_config.0.ipsec_auth_alg: "md5"
      ipsec_config.0.ipsec_enc_alg:  "des"
      ipsec_config.0.ipsec_lifetime: "8640"
      ipsec_config.0.ipsec_pfs:      "group5"
      local_subnet.#:                "2"
      local_subnet.2201616582:       "192.168.1.0/24"
      local_subnet.3000113755:       "192.168.2.0/24"
      name:                          "vco-instance-name"
      remote_subnet.#:               "2"
      remote_subnet.1474686024:      "172.16.3.0/24"
      remote_subnet.4052936700:      "172.16.2.0/24"
      status:                        <computed>
      vpn_gateway_id:                "${alicloud_vpn_gateway.vpngw.id}"

  + module.vpn.alicloud_vpn_customer_gateway.vpncgw
      id:                            <computed>
      description:                   "xxxxxx"
      ip_address:                    "21.37.166.152"
      name:                          "cgw-instance-name"

  + module.vpn.alicloud_vpn_gateway.vpngw
      id:                            <computed>
      bandwidth:                     "10"
      business_status:               <computed>
      description:                   "xxxxx"
      enable_ipsec:                  "true"
      enable_ssl:                    "true"
      instance_charge_type:          "PostPaid"
      internet_ip:                   <computed>
      name:                          "vpn-instance-name"
      period:                        "1"
      ssl_connections:               "5"
      status:                        <computed>
      vpc_id:                        "vpc-2ze26284hzdqxew4nll0t"


Plan: 6 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.vpn.alicloud_vpn_customer_gateway.vpncgw: Creating...
  description: "" => "xxxxxx"
  ip_address:  "" => "21.37.166.152"
  name:        "" => "cgw-instance-name"
module.vpn.alicloud_vpn_gateway.vpngw: Creating...
  bandwidth:            "" => "10"
  business_status:      "" => "<computed>"
  description:          "" => "xxxxx"
  enable_ipsec:         "" => "true"
  enable_ssl:           "" => "true"
  instance_charge_type: "" => "PostPaid"
  internet_ip:          "" => "<computed>"
  name:                 "" => "vpn-instance-name"
  period:               "" => "1"
  ssl_connections:      "" => "5"
  status:               "" => "<computed>"
  vpc_id:               "" => "vpc-2ze26284hzdqxew4nll0t"
module.vpn.alicloud_vpn_customer_gateway.vpncgw: Creation complete after 9s (ID: cgw-2zes7j7lfaxrog9mjb4r8)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (10s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (20s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (30s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (40s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (50s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (1m0s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (1m10s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (1m20s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (1m30s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Creation complete after 1m35s (ID: vpn-2zem1hbpt44cbvqyk2i42)
module.vpn.alicloud_ssl_vpn_server.sslserver: Creating...
  cipher:          "" => "AES-128-CBC"
  client_ip_pool:  "" => "192.168.10.0/24"
  compress:        "" => "false"
  connections:     "" => "<computed>"
  internet_ip:     "" => "<computed>"
  local_subnet:    "" => "172.16.1.0/24"
  max_connections: "" => "<computed>"
  name:            "" => "vss-instance-name"
  port:            "" => "1194"
  protocol:        "" => "UDP"
  vpn_gateway_id:  "" => "vpn-2zem1hbpt44cbvqyk2i42"
module.vpn.alicloud_vpn_connection.connection: Creating...
  customer_gateway_id:           "" => "cgw-2zes7j7lfaxrog9mjb4r8"
  effect_immediately:            "" => "true"
  ike_config.#:                  "" => "1"
  ike_config.0.ike_auth_alg:     "" => "md5"
  ike_config.0.ike_enc_alg:      "" => "des"
  ike_config.0.ike_lifetime:     "" => "86400"
  ike_config.0.ike_local_id:     "" => "test-local-id"
  ike_config.0.ike_mode:         "" => "main"
  ike_config.0.ike_pfs:          "" => "group1"
  ike_config.0.ike_remote_id:    "" => "test-remote-id"
  ike_config.0.ike_version:      "" => "ikev2"
  ike_config.0.psk:              "" => "tf-testvpn"
  ipsec_config.#:                "" => "1"
  ipsec_config.0.ipsec_auth_alg: "" => "md5"
  ipsec_config.0.ipsec_enc_alg:  "" => "des"
  ipsec_config.0.ipsec_lifetime: "" => "8640"
  ipsec_config.0.ipsec_pfs:      "" => "group5"
  local_subnet.#:                "" => "2"
  local_subnet.2201616582:       "" => "192.168.1.0/24"
  local_subnet.3000113755:       "" => "192.168.2.0/24"
  name:                          "" => "vco-instance-name"
  remote_subnet.#:               "" => "2"
  remote_subnet.1474686024:      "" => "172.16.3.0/24"
  remote_subnet.4052936700:      "" => "172.16.2.0/24"
  status:                        "" => "<computed>"
  vpn_gateway_id:                "" => "vpn-2zem1hbpt44cbvqyk2i42"
module.vpn.alicloud_ssl_vpn_server.sslserver: Creation complete after 2s (ID: vss-2ze [...]

2019-04-10 13:32 UTC, ali-zhuyu commented
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

alicloud_vpn_gateway.vpngw: Refreshing state... (ID: vpn-2zem1hbpt44cbvqyk2i42)
alicloud_vpn_customer_gateway.vpncgw: Refreshing state... (ID: cgw-2zes7j7lfaxrog9mjb4r8)
alicloud_ssl_vpn_server.sslserver: Refreshing state... (ID: vss-2zekb0uqgcsbgx7ozhhw6)
alicloud_vpn_connection.connection: Refreshing state... (ID: vco-2zewm9por0ntee3zgr6xk)
alicloud_ssl_vpn_client_cert.certs[0]: Refreshing state... (ID: vsc-2ze7fq5u0f7xhoxl9vefr)
alicloud_ssl_vpn_client_cert.certs[1]: Refreshing state... (ID: vsc-2zeu5l3qmf7rl64jg25gz)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

2019-04-10 13:32 UTC, ali-zhuyu commented
terraform destroy
alicloud_vpn_customer_gateway.vpncgw: Refreshing state... (ID: cgw-2zes7j7lfaxrog9mjb4r8)
alicloud_vpn_gateway.vpngw: Refreshing state... (ID: vpn-2zem1hbpt44cbvqyk2i42)
alicloud_ssl_vpn_server.sslserver: Refreshing state... (ID: vss-2zekb0uqgcsbgx7ozhhw6)
alicloud_vpn_connection.connection: Refreshing state... (ID: vco-2zewm9por0ntee3zgr6xk)
alicloud_ssl_vpn_client_cert.certs[1]: Refreshing state... (ID: vsc-2zeu5l3qmf7rl64jg25gz)
alicloud_ssl_vpn_client_cert.certs[0]: Refreshing state... (ID: vsc-2ze7fq5u0f7xhoxl9vefr)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - module.vpn.alicloud_ssl_vpn_client_cert.certs[0]

  - module.vpn.alicloud_ssl_vpn_client_cert.certs[1]

  - module.vpn.alicloud_ssl_vpn_server.sslserver

  - module.vpn.alicloud_vpn_connection.connection

  - module.vpn.alicloud_vpn_customer_gateway.vpncgw

  - module.vpn.alicloud_vpn_gateway.vpngw


Plan: 0 to add, 0 to change, 6 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

module.vpn.alicloud_vpn_connection.connection: Destroying... (ID: vco-2zewm9por0ntee3zgr6xk)
module.vpn.alicloud_ssl_vpn_client_cert.certs[0]: Destroying... (ID: vsc-2ze7fq5u0f7xhoxl9vefr)
module.vpn.alicloud_ssl_vpn_client_cert.certs[1]: Destroying... (ID: vsc-2zeu5l3qmf7rl64jg25gz)
module.vpn.alicloud_ssl_vpn_client_cert.certs[0]: Destruction complete after 0s
module.vpn.alicloud_ssl_vpn_client_cert.certs[1]: Destruction complete after 8s
module.vpn.alicloud_ssl_vpn_server.sslserver: Destroying... (ID: vss-2zekb0uqgcsbgx7ozhhw6)
module.vpn.alicloud_vpn_connection.connection: Still destroying... (ID: vco-2zewm9por0ntee3zgr6xk, 10s elapsed)
module.vpn.alicloud_ssl_vpn_server.sslserver: Still destroying... (ID: vss-2zekb0uqgcsbgx7ozhhw6, 10s elapsed)
module.vpn.alicloud_ssl_vpn_server.sslserver: Destruction complete after 11s
module.vpn.alicloud_vpn_connection.connection: Still destroying... (ID: vco-2zewm9por0ntee3zgr6xk, 20s elapsed)
module.vpn.alicloud_vpn_connection.connection: Destruction complete after 22s
module.vpn.alicloud_vpn_customer_gateway.vpncgw: Destroying... (ID: cgw-2zes7j7lfaxrog9mjb4r8)
module.vpn.alicloud_vpn_gateway.vpngw: Destroying... (ID: vpn-2zem1hbpt44cbvqyk2i42)
module.vpn.alicloud_vpn_customer_gateway.vpncgw: Destruction complete after 0s
module.vpn.alicloud_vpn_gateway.vpngw: Destruction complete after 2s

Destroy complete! Resources: 6 destroyed.

2019-04-15 09:48 UTC, xiaozhu36 requested changes

2019-04-15 09:48 UTC, xiaozhu36 commented on README.md
> +
There should show some resources in which this module.

2019-04-15 09:48 UTC, xiaozhu36 commented on outputs.tf
> +  value       = "${join(",", alicloud_vpn_connection.connection.*.id)}"
Please set the output parameters with `this_` prefix.

2019-04-15 10:22 UTC, ali-zhuyu commented
terraform init
Initializing modules...
- module.vpn

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

2019-04-15 10:23 UTC, ali-zhuyu commented
terraform apply
alicloud_vpn_customer_gateway.vpncgw: Refreshing state... (ID: cgw-2ze9pg69d66ad6v9j65ue)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + module.vpn.alicloud_ssl_vpn_client_cert.certs[0]
      id:                            <computed>
      name:                          "vsc-instance-name1"
      ssl_vpn_server_id:             "${alicloud_ssl_vpn_server.sslserver.id}"
      status:                        <computed>

  + module.vpn.alicloud_ssl_vpn_client_cert.certs[1]
      id:                            <computed>
      name:                          "vsc-instance-name2"
      ssl_vpn_server_id:             "${alicloud_ssl_vpn_server.sslserver.id}"
      status:                        <computed>

  + module.vpn.alicloud_ssl_vpn_server.sslserver
      id:                            <computed>
      cipher:                        "AES-128-CBC"
      client_ip_pool:                "192.168.10.0/24"
      compress:                      "false"
      connections:                   <computed>
      internet_ip:                   <computed>
      local_subnet:                  "172.16.1.0/24"
      max_connections:               <computed>
      name:                          "vss-instance-name"
      port:                          "1194"
      protocol:                      "UDP"
      vpn_gateway_id:                "${alicloud_vpn_gateway.vpngw.id}"

  + module.vpn.alicloud_vpn_connection.connection
      id:                            <computed>
      customer_gateway_id:           "cgw-2ze9pg69d66ad6v9j65ue"
      effect_immediately:            "true"
      ike_config.#:                  "1"
      ike_config.0.ike_auth_alg:     "md5"
      ike_config.0.ike_enc_alg:      "des"
      ike_config.0.ike_lifetime:     "86400"
      ike_config.0.ike_local_id:     "test-local-id"
      ike_config.0.ike_mode:         "main"
      ike_config.0.ike_pfs:          "group1"
      ike_config.0.ike_remote_id:    "test-remote-id"
      ike_config.0.ike_version:      "ikev2"
      ike_config.0.psk:              "tf-testvpn"
      ipsec_config.#:                "1"
      ipsec_config.0.ipsec_auth_alg: "md5"
      ipsec_config.0.ipsec_enc_alg:  "des"
      ipsec_config.0.ipsec_lifetime: "8640"
      ipsec_config.0.ipsec_pfs:      "group5"
      local_subnet.#:                "2"
      local_subnet.2201616582:       "192.168.1.0/24"
      local_subnet.3000113755:       "192.168.2.0/24"
      name:                          "vco-instance-name"
      remote_subnet.#:               "2"
      remote_subnet.1474686024:      "172.16.3.0/24"
      remote_subnet.4052936700:      "172.16.2.0/24"
      status:                        <computed>
      vpn_gateway_id:                "${alicloud_vpn_gateway.vpngw.id}"

  + module.vpn.alicloud_vpn_gateway.vpngw
      id:                            <computed>
      bandwidth:                     "10"
      business_status:               <computed>
      description:                   "xxxxx"
      enable_ipsec:                  "true"
      enable_ssl:                    "true"
      instance_charge_type:          "PostPaid"
      internet_ip:                   <computed>
      name:                          "vpn-instance-name"
      period:                        "1"
      ssl_connections:               "5"
      status:                        <computed>
      vpc_id:                        "vpc-2zeybjkt3jjn5ec9njzf9"


Plan: 5 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.vpn.alicloud_vpn_gateway.vpngw: Creating...
  bandwidth:            "" => "10"
  business_status:      "" => "<computed>"
  description:          "" => "xxxxx"
  enable_ipsec:         "" => "true"
  enable_ssl:           "" => "true"
  instance_charge_type: "" => "PostPaid"
  internet_ip:          "" => "<computed>"
  name:                 "" => "vpn-instance-name"
  period:               "" => "1"
  ssl_connections:      "" => "5"
  status:               "" => "<computed>"
  vpc_id:               "" => "vpc-2zeybjkt3jjn5ec9njzf9"
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (10s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (20s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (30s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (40s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (50s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (1m0s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (1m10s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (1m20s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (1m30s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Creation complete after 1m34s (ID: vpn-2zedqoxpm1smgig5ihk6f)
module.vpn.alicloud_ssl_vpn_server.sslserver: Creating...
  cipher:          "" => "AES-128-CBC"
  client_ip_pool:  "" => "192.168.10.0/24"
  compress:        "" => "false"
  connections:     "" => "<computed>"
  internet_ip:     "" => "<computed>"
  local_subnet:    "" => "172.16.1.0/24"
  max_connections: "" => "<computed>"
  name:            "" => "vss-instance-name"
  port:            "" => "1194"
  protocol:        "" => "UDP"
  vpn_gateway_id:  "" => "vpn-2zedqoxpm1smgig5ihk6f"
module.vpn.alicloud_vpn_connection.connection: Creating...
  customer_gateway_id:           "" => "cgw-2ze9pg69d66ad6v9j65ue"
  effect_immediately:            "" => "true"
  ike_config.#:                  "" => "1"
  ike_config.0.ike_auth_alg:     "" => "md5"
  ike_config.0.ike_enc_alg:      "" => "des"
  ike_config.0.ike_lifetime:     "" => "86400"
  ike_config.0.ike_local_id:     "" => "test-local-id"
  ike_config.0.ike_mode:         "" => "main"
  ike_config.0.ike_pfs:          "" => "group1"
  ike_config.0.ike_remote_id:    "" => "test-remote-id"
  ike_config.0.ike_version:      "" => "ikev2"
  ike_config.0.psk:              "" => "tf-testvpn"
  ipsec_config.#:                "" => "1"
  ipsec_config.0.ipsec_auth_alg: "" => "md5"
  ipsec_config.0.ipsec_enc_alg:  "" => "des"
  ipsec_config.0.ipsec_lifetime: "" => "8640"
  ipsec_config.0.ipsec_pfs:      "" => "group5"
  local_subnet.#:                "" => "2"
  local_subnet.2201616582:       "" => "192.168.1.0/24"
  local_subnet.3000113755:       "" => "192.168.2.0/24"
  name:                          "" => "vco-instance-name"
  remote_subnet.#:               "" => "2"
  remote_subnet.1474686024:      "" => "172.16.3.0/24"
  remote_subnet.4052936700:      "" => "172.16.2.0/24"
  status:                        "" => "<computed>"
  vpn_gateway_id:                "" => "vpn-2zedqoxpm1smgig5ihk6f"
module.vpn.alicloud_ssl_vpn_server.sslserver: Creation complete after 3s (ID: vss-2zed5pce8qew8tx4vihw7)
module.vpn.alicloud_ssl_vpn_client_cert.certs[0]: Creating...
  name:              "" => "vsc-instance-name1"
  ssl_vpn_server_id: "" => "vss-2zed5pce8qew8tx4vihw7"
  status:            "" => "<computed>"
module.vpn.alicloud_ssl_vpn_client_cert.certs[1]: Creating...
  name:              "" => "vsc-instance-name2"
  ssl_vpn_server_id: "" => "vss-2zed5pce8qew8tx4vihw7"
  status:            "" => "<computed>"
module.vpn.alicloud_vpn_connection.connection: Still creating... (10s elapsed)
module.vpn.alicloud_ssl_vpn_client_cert.certs[0]: Creation complete after 10s (ID: vsc-2zeti6yss9wq9mcxe4odk)
module.vpn.alicloud_ssl_vpn_client_cert.certs.1: Still creating... (10s elapsed)
module.vpn.alicloud_ssl_vpn_client_cert.certs[1]: Creation complete after 11s (ID: vsc-2zejzmpzotdcysh4ev21k)
module.vpn.alicloud_vpn_connection.connection: Creation complete after 15s (ID: vco-2zebm4umvdvrq5j9uhht5)

Apply complete! Resources: 5 added, 0 changed, 0 destroyed.

Outputs:

cgw_id = cgw-2ze9pg69d66ad6v9j65u [...]

2019-04-15 10:23 UTC, ali-zhuyu commented
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

alicloud_vpn_gateway.vpngw: Refreshing state... (ID: vpn-2zedqoxpm1smgig5ihk6f)
alicloud_vpn_customer_gateway.vpncgw: Refreshing state... (ID: cgw-2ze9pg69d66ad6v9j65ue)
alicloud_ssl_vpn_server.sslserver: Refreshing state... (ID: vss-2zed5pce8qew8tx4vihw7)
alicloud_vpn_connection.connection: Refreshing state... (ID: vco-2zebm4umvdvrq5j9uhht5)
alicloud_ssl_vpn_client_cert.certs[0]: Refreshing state... (ID: vsc-2zeti6yss9wq9mcxe4odk)
alicloud_ssl_vpn_client_cert.certs[1]: Refreshing state... (ID: vsc-2zejzmpzotdcysh4ev21k)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

2019-04-15 10:23 UTC, ali-zhuyu commented
terraform destroy
alicloud_vpn_gateway.vpngw: Refreshing state... (ID: vpn-2zedqoxpm1smgig5ihk6f)
alicloud_vpn_customer_gateway.vpncgw: Refreshing state... (ID: cgw-2ze9pg69d66ad6v9j65ue)
alicloud_vpn_connection.connection: Refreshing state... (ID: vco-2zebm4umvdvrq5j9uhht5)
alicloud_ssl_vpn_server.sslserver: Refreshing state... (ID: vss-2zed5pce8qew8tx4vihw7)
alicloud_ssl_vpn_client_cert.certs[0]: Refreshing state... (ID: vsc-2zeti6yss9wq9mcxe4odk)
alicloud_ssl_vpn_client_cert.certs[1]: Refreshing state... (ID: vsc-2zejzmpzotdcysh4ev21k)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - module.vpn.alicloud_ssl_vpn_client_cert.certs[0]

  - module.vpn.alicloud_ssl_vpn_client_cert.certs[1]

  - module.vpn.alicloud_ssl_vpn_server.sslserver

  - module.vpn.alicloud_vpn_connection.connection

  - module.vpn.alicloud_vpn_customer_gateway.vpncgw

  - module.vpn.alicloud_vpn_gateway.vpngw


Plan: 0 to add, 0 to change, 6 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

module.vpn.alicloud_ssl_vpn_client_cert.certs[1]: Destroying... (ID: vsc-2zejzmpzotdcysh4ev21k)
module.vpn.alicloud_vpn_connection.connection: Destroying... (ID: vco-2zebm4umvdvrq5j9uhht5)
module.vpn.alicloud_ssl_vpn_client_cert.certs[0]: Destroying... (ID: vsc-2zeti6yss9wq9mcxe4odk)
module.vpn.alicloud_ssl_vpn_client_cert.certs[1]: Destruction complete after 1s
module.vpn.alicloud_vpn_connection.connection: Still destroying... (ID: vco-2zebm4umvdvrq5j9uhht5, 10s elapsed)
module.vpn.alicloud_ssl_vpn_client_cert.certs.0: Still destroying... (ID: vsc-2zeti6yss9wq9mcxe4odk, 10s elapsed)
module.vpn.alicloud_vpn_connection.connection: Destruction complete after 12s
module.vpn.alicloud_vpn_customer_gateway.vpncgw: Destroying... (ID: cgw-2ze9pg69d66ad6v9j65ue)
module.vpn.alicloud_vpn_customer_gateway.vpncgw: Destruction complete after 0s
module.vpn.alicloud_ssl_vpn_client_cert.certs[0]: Destruction complete after 17s
module.vpn.alicloud_ssl_vpn_server.sslserver: Destroying... (ID: vss-2zed5pce8qew8tx4vihw7)
module.vpn.alicloud_ssl_vpn_server.sslserver: Still destroying... (ID: vss-2zed5pce8qew8tx4vihw7, 10s elapsed)
module.vpn.alicloud_ssl_vpn_server.sslserver: Destruction complete after 11s
module.vpn.alicloud_vpn_gateway.vpngw: Destroying... (ID: vpn-2zedqoxpm1smgig5ihk6f)
module.vpn.alicloud_vpn_gateway.vpngw: Destruction complete after 1s

Destroy complete! Resources: 6 destroyed.

2019-04-15 10:46 UTC, ali-zhuyu commented
terraform init
Initializing modules...
- module.vpn

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

2019-04-15 10:47 UTC, ali-zhuyu commented
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + module.vpn.alicloud_ssl_vpn_client_cert.certs[0]
      id:                            <computed>
      name:                          "vsc-instance-name1"
      ssl_vpn_server_id:             "${alicloud_ssl_vpn_server.sslserver.id}"
      status:                        <computed>

  + module.vpn.alicloud_ssl_vpn_client_cert.certs[1]
      id:                            <computed>
      name:                          "vsc-instance-name2"
      ssl_vpn_server_id:             "${alicloud_ssl_vpn_server.sslserver.id}"
      status:                        <computed>

  + module.vpn.alicloud_ssl_vpn_server.sslserver
      id:                            <computed>
      cipher:                        "AES-128-CBC"
      client_ip_pool:                "192.168.10.0/24"
      compress:                      "false"
      connections:                   <computed>
      internet_ip:                   <computed>
      local_subnet:                  "172.16.1.0/24"
      max_connections:               <computed>
      name:                          "vss-instance-name"
      port:                          "1194"
      protocol:                      "UDP"
      vpn_gateway_id:                "${alicloud_vpn_gateway.vpngw.id}"

  + module.vpn.alicloud_vpn_connection.connection
      id:                            <computed>
      customer_gateway_id:           "${var.cgw_id != \"\" ? var.cgw_id : alicloud_vpn_customer_gateway.vpncgw.id}"
      effect_immediately:            "true"
      ike_config.#:                  "1"
      ike_config.0.ike_auth_alg:     "md5"
      ike_config.0.ike_enc_alg:      "des"
      ike_config.0.ike_lifetime:     "86400"
      ike_config.0.ike_local_id:     "test-local-id"
      ike_config.0.ike_mode:         "main"
      ike_config.0.ike_pfs:          "group1"
      ike_config.0.ike_remote_id:    "test-remote-id"
      ike_config.0.ike_version:      "ikev2"
      ike_config.0.psk:              "tf-testvpn"
      ipsec_config.#:                "1"
      ipsec_config.0.ipsec_auth_alg: "md5"
      ipsec_config.0.ipsec_enc_alg:  "des"
      ipsec_config.0.ipsec_lifetime: "8640"
      ipsec_config.0.ipsec_pfs:      "group5"
      local_subnet.#:                "2"
      local_subnet.2201616582:       "192.168.1.0/24"
      local_subnet.3000113755:       "192.168.2.0/24"
      name:                          "vco-instance-name"
      remote_subnet.#:               "2"
      remote_subnet.1474686024:      "172.16.3.0/24"
      remote_subnet.4052936700:      "172.16.2.0/24"
      status:                        <computed>
      vpn_gateway_id:                "${alicloud_vpn_gateway.vpngw.id}"

  + module.vpn.alicloud_vpn_customer_gateway.vpncgw
      id:                            <computed>
      description:                   "xxxxxx"
      ip_address:                    "21.37.166.152"
      name:                          "cgw-instance-name"

  + module.vpn.alicloud_vpn_gateway.vpngw
      id:                            <computed>
      bandwidth:                     "10"
      business_status:               <computed>
      description:                   "xxxxx"
      enable_ipsec:                  "true"
      enable_ssl:                    "true"
      instance_charge_type:          "PostPaid"
      internet_ip:                   <computed>
      name:                          "vpn-instance-name"
      period:                        "1"
      ssl_connections:               "5"
      status:                        <computed>
      vpc_id:                        "vpc-2zeybjkt3jjn5ec9njzf9"


Plan: 6 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

2019-04-15 10:47 UTC, ali-zhuyu commented
terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + module.vpn.alicloud_ssl_vpn_client_cert.certs[0]
      id:                            <computed>
      name:                          "vsc-instance-name1"
      ssl_vpn_server_id:             "${alicloud_ssl_vpn_server.sslserver.id}"
      status:                        <computed>

  + module.vpn.alicloud_ssl_vpn_client_cert.certs[1]
      id:                            <computed>
      name:                          "vsc-instance-name2"
      ssl_vpn_server_id:             "${alicloud_ssl_vpn_server.sslserver.id}"
      status:                        <computed>

  + module.vpn.alicloud_ssl_vpn_server.sslserver
      id:                            <computed>
      cipher:                        "AES-128-CBC"
      client_ip_pool:                "192.168.10.0/24"
      compress:                      "false"
      connections:                   <computed>
      internet_ip:                   <computed>
      local_subnet:                  "172.16.1.0/24"
      max_connections:               <computed>
      name:                          "vss-instance-name"
      port:                          "1194"
      protocol:                      "UDP"
      vpn_gateway_id:                "${alicloud_vpn_gateway.vpngw.id}"

  + module.vpn.alicloud_vpn_connection.connection
      id:                            <computed>
      customer_gateway_id:           "${var.cgw_id != \"\" ? var.cgw_id : alicloud_vpn_customer_gateway.vpncgw.id}"
      effect_immediately:            "true"
      ike_config.#:                  "1"
      ike_config.0.ike_auth_alg:     "md5"
      ike_config.0.ike_enc_alg:      "des"
      ike_config.0.ike_lifetime:     "86400"
      ike_config.0.ike_local_id:     "test-local-id"
      ike_config.0.ike_mode:         "main"
      ike_config.0.ike_pfs:          "group1"
      ike_config.0.ike_remote_id:    "test-remote-id"
      ike_config.0.ike_version:      "ikev2"
      ike_config.0.psk:              "tf-testvpn"
      ipsec_config.#:                "1"
      ipsec_config.0.ipsec_auth_alg: "md5"
      ipsec_config.0.ipsec_enc_alg:  "des"
      ipsec_config.0.ipsec_lifetime: "8640"
      ipsec_config.0.ipsec_pfs:      "group5"
      local_subnet.#:                "2"
      local_subnet.2201616582:       "192.168.1.0/24"
      local_subnet.3000113755:       "192.168.2.0/24"
      name:                          "vco-instance-name"
      remote_subnet.#:               "2"
      remote_subnet.1474686024:      "172.16.3.0/24"
      remote_subnet.4052936700:      "172.16.2.0/24"
      status:                        <computed>
      vpn_gateway_id:                "${alicloud_vpn_gateway.vpngw.id}"

  + module.vpn.alicloud_vpn_customer_gateway.vpncgw
      id:                            <computed>
      description:                   "xxxxxx"
      ip_address:                    "21.37.166.152"
      name:                          "cgw-instance-name"

  + module.vpn.alicloud_vpn_gateway.vpngw
      id:                            <computed>
      bandwidth:                     "10"
      business_status:               <computed>
      description:                   "xxxxx"
      enable_ipsec:                  "true"
      enable_ssl:                    "true"
      instance_charge_type:          "PostPaid"
      internet_ip:                   <computed>
      name:                          "vpn-instance-name"
      period:                        "1"
      ssl_connections:               "5"
      status:                        <computed>
      vpc_id:                        "vpc-2zeybjkt3jjn5ec9njzf9"


Plan: 6 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.vpn.alicloud_vpn_customer_gateway.vpncgw: Creating...
  description: "" => "xxxxxx"
  ip_address:  "" => "21.37.166.152"
  name:        "" => "cgw-instance-name"
module.vpn.alicloud_vpn_gateway.vpngw: Creating...
  bandwidth:            "" => "10"
  business_status:      "" => "<computed>"
  description:          "" => "xxxxx"
  enable_ipsec:         "" => "true"
  enable_ssl:           "" => "true"
  instance_charge_type: "" => "PostPaid"
  internet_ip:          "" => "<computed>"
  name:                 "" => "vpn-instance-name"
  period:               "" => "1"
  ssl_connections:      "" => "5"
  status:               "" => "<computed>"
  vpc_id:               "" => "vpc-2zeybjkt3jjn5ec9njzf9"
module.vpn.alicloud_vpn_customer_gateway.vpncgw: Creation complete after 10s (ID: cgw-2zehgz0tk8vod1h0o8lfd)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (10s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (20s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (30s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (40s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (50s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (1m0s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (1m10s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (1m20s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Still creating... (1m30s elapsed)
module.vpn.alicloud_vpn_gateway.vpngw: Creation complete after 1m40s (ID: vpn-2zeo1axuejvdfyeib6mg4)
module.vpn.alicloud_ssl_vpn_server.sslserver: Creating...
  cipher:          "" => "AES-128-CBC"
  client_ip_pool:  "" => "192.168.10.0/24"
  compress:        "" => "false"
  connections:     "" => "<computed>"
  internet_ip:     "" => "<computed>"
  local_subnet:    "" => "172.16.1.0/24"
  max_connections: "" => "<computed>"
  name:            "" => "vss-instance-name"
  port:            "" => "1194"
  protocol:        "" => "UDP"
  vpn_gateway_id:  "" => "vpn-2zeo1axuejvdfyeib6mg4"
module.vpn.alicloud_vpn_connection.connection: Creating...
  customer_gateway_id:           "" => "cgw-2zehgz0tk8vod1h0o8lfd"
  effect_immediately:            "" => "true"
  ike_config.#:                  "" => "1"
  ike_config.0.ike_auth_alg:     "" => "md5"
  ike_config.0.ike_enc_alg:      "" => "des"
  ike_config.0.ike_lifetime:     "" => "86400"
  ike_config.0.ike_local_id:     "" => "test-local-id"
  ike_config.0.ike_mode:         "" => "main"
  ike_config.0.ike_pfs:          "" => "group1"
  ike_config.0.ike_remote_id:    "" => "test-remote-id"
  ike_config.0.ike_version:      "" => "ikev2"
  ike_config.0.psk:              "" => "tf-testvpn"
  ipsec_config.#:                "" => "1"
  ipsec_config.0.ipsec_auth_alg: "" => "md5"
  ipsec_config.0.ipsec_enc_alg:  "" => "des"
  ipsec_config.0.ipsec_lifetime: "" => "8640"
  ipsec_config.0.ipsec_pfs:      "" => "group5"
  local_subnet.#:                "" => "2"
  local_subnet.2201616582:       "" => "192.168.1.0/24"
  local_subnet.3000113755:       "" => "192.168.2.0/24"
  name:                          "" => "vco-instance-name"
  remote_subnet.#:               "" => "2"
  remote_subnet.1474686024:      "" => "172.16.3.0/24"
  remote_subnet.4052936700:      "" => "172.16.2.0/24"
  status:                        "" => "<computed>"
  vpn_gateway_id:                "" => "vpn-2zeo1axuejvdfyeib6mg4"
module.vpn.alicloud_ssl_vpn_server.sslserver: Creation complete after 2s (ID: vss-2zekaagltyo317m225f96)
module.vpn.alicloud_ssl_vpn_client_cert.certs[1]: Creating...
  name:              "" => "vsc-instance-name2"
  ssl_vpn_server_id: "" => "vss-2zekaagltyo317m225f96"
  status:            "" => "<computed>"
module.vpn.alicloud_ssl_vpn_client_cert.certs[0]: Creating...
  name:              "" => "vsc-instance-name1"
  ssl_vpn_server_id: "" => "vss-2zekaagltyo317m225f96"
  status:            "" => "<computed>"
module.vpn.alicloud_vpn_connection.connection: Still creating... (10s elapsed)
module.vpn.aliclo [...]

2019-04-15 10:47 UTC, ali-zhuyu commented
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

alicloud_vpn_gateway.vpngw: Refreshing state... (ID: vpn-2zeo1axuejvdfyeib6mg4)
alicloud_vpn_customer_gateway.vpncgw: Refreshing state... (ID: cgw-2zehgz0tk8vod1h0o8lfd)
alicloud_ssl_vpn_server.sslserver: Refreshing state... (ID: vss-2zekaagltyo317m225f96)
alicloud_vpn_connection.connection: Refreshing state... (ID: vco-2zeg9nklw5iv6o6aqog86)
alicloud_ssl_vpn_client_cert.certs[0]: Refreshing state... (ID: vsc-2zey80nwpzt6fte11ifzv)
alicloud_ssl_vpn_client_cert.certs[1]: Refreshing state... (ID: vsc-2zedxt03gnwliy07cmhid)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

2019-04-15 10:47 UTC, ali-zhuyu commented
terraform destroy
alicloud_vpn_customer_gateway.vpncgw: Refreshing state... (ID: cgw-2zehgz0tk8vod1h0o8lfd)
alicloud_vpn_gateway.vpngw: Refreshing state... (ID: vpn-2zeo1axuejvdfyeib6mg4)
alicloud_vpn_connection.connection: Refreshing state... (ID: vco-2zeg9nklw5iv6o6aqog86)
alicloud_ssl_vpn_server.sslserver: Refreshing state... (ID: vss-2zekaagltyo317m225f96)
alicloud_ssl_vpn_client_cert.certs[0]: Refreshing state... (ID: vsc-2zey80nwpzt6fte11ifzv)
alicloud_ssl_vpn_client_cert.certs[1]: Refreshing state... (ID: vsc-2zedxt03gnwliy07cmhid)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - module.vpn.alicloud_ssl_vpn_client_cert.certs[0]

  - module.vpn.alicloud_ssl_vpn_client_cert.certs[1]

  - module.vpn.alicloud_ssl_vpn_server.sslserver

  - module.vpn.alicloud_vpn_connection.connection

  - module.vpn.alicloud_vpn_customer_gateway.vpncgw

  - module.vpn.alicloud_vpn_gateway.vpngw


Plan: 0 to add, 0 to change, 6 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

module.vpn.alicloud_vpn_connection.connection: Destroying... (ID: vco-2zeg9nklw5iv6o6aqog86)
module.vpn.alicloud_ssl_vpn_client_cert.certs[1]: Destroying... (ID: vsc-2zedxt03gnwliy07cmhid)
module.vpn.alicloud_ssl_vpn_client_cert.certs[0]: Destroying... (ID: vsc-2zey80nwpzt6fte11ifzv)
module.vpn.alicloud_vpn_connection.connection: Destruction complete after 1s
module.vpn.alicloud_vpn_customer_gateway.vpncgw: Destroying... (ID: cgw-2zehgz0tk8vod1h0o8lfd)
module.vpn.alicloud_vpn_customer_gateway.vpncgw: Destruction complete after 0s
module.vpn.alicloud_ssl_vpn_client_cert.certs[1]: Destruction complete after 1s
module.vpn.alicloud_ssl_vpn_client_cert.certs.0: Still destroying... (ID: vsc-2zey80nwpzt6fte11ifzv, 10s elapsed)
module.vpn.alicloud_ssl_vpn_client_cert.certs[0]: Destruction complete after 17s
module.vpn.alicloud_ssl_vpn_server.sslserver: Destroying... (ID: vss-2zekaagltyo317m225f96)
module.vpn.alicloud_ssl_vpn_server.sslserver: Still destroying... (ID: vss-2zekaagltyo317m225f96, 10s elapsed)
module.vpn.alicloud_ssl_vpn_server.sslserver: Destruction complete after 11s
module.vpn.alicloud_vpn_gateway.vpngw: Destroying... (ID: vpn-2zeo1axuejvdfyeib6mg4)
module.vpn.alicloud_vpn_gateway.vpngw: Destruction complete after 2s

Destroy complete! Resources: 6 destroyed.

2019-04-15 11:15 UTC, xiaozhu36 approved these changes

2019-04-15 11:16 UTC, merged